name: Build and publish

on:
  schedule:
    - cron:  '0 4 * * *'
  workflow_dispatch:


jobs:
  docker:
    name: Build and publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Latest Tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: looterz/grimd
          releases-only: true
        id: latest

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            dbrbc/grimd
            ghcr.io/dbrbc/grimd

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          build-args: VERSION=${{ steps.latest.outputs.tag }}
          platforms: linux/arm,linux/arm64,linux/amd64
          push: true
          tags: ${{ steps.latest.outputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}